[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "15.0.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "10.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/lawrencegripper/pod2docker"
  version = "0.5.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/twinj/uuid"
  version = "1.0.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.9.2"

[[constraint]]
  name = "pack.ag/amqp"
  version = "0.5.0" 

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
