apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      application: {{ template "fullname" . }}
      component: {{ template "name" . }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        application: {{ template "fullname" . }}
        component: {{ template "name" . }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if and (.Values.tolerations) (ge .Capabilities.KubeVersion.Minor "6") }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DISPATCHER_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DISPATCHER_MODULE_TYPE
          value: {{ .Values.module.type }}
        - name: DISPATCHER_MODULE_IMAGE
          value: "{{ .Values.module.image.name }}:{{ .Values.module.image.tag }}"
        - name: DISPATCHER_MODULE_EVENTSPUBLISHED
          value: {{ .Values.module.eventsPublished }}
        - name: DISPATCHER_MODULE_MAXRUNNINGTIMEMINS
          value: {{ .Values.module.maxRunningTimeMins | quote }}
        - name: DISPATCHER_MODULE_RETRYCOUNT
          value: {{ .Values.module.retryCount | quote }}
        - name: DISPATCHER_MODULE_SUBSCRIBESTOEVENT
          value: {{ .Values.module.subscribesToEvent }}
        - name: DISPATCHER_MODULE_CONFIG_PATH
          value: /etc/ion/module/config.yml
        - name: DISPATCHER_MODULE_SIDECAR_HOST
          value: {{ .Values.module.sidecar.host | quote }}
        - name: DISPATCHER_MODULE_SIDECAR_IMAGE
          value: "{{ .Values.module.sidecar.image.name }}:{{ .Values.module.sidecar.image.tag }}"
        - name: DISPATCHER_MODULE_SIDECAR_PRINTCONFIG
          value: {{ .Values.module.sidecar.printConfig | quote }}
        - name: DISPATCHER_LOG_LEVEL
          value: {{ .Values.log.level }}
        - name: DISPATCHER_LOG_SENSITIVE
          value: {{ .Values.log.sensitive | quote }}
        {{- if .Values.cloud.azure }}
        - name: DISPATCHER_CLOUD_AZURE_CLIENTID
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: azureClientId
        - name: DISPATCHER_CLOUD_AZURE_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: azureClientSecret
        - name: DISPATCHER_CLOUD_AZURE_TENANTID
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: azureTenantId
        - name: DISPATCHER_CLOUD_AZURE_SUBSCRIPTIONID
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: azureSubscriptionId
        - name: DISPATCHER_CLOUD_AZURE_RESOURCEGROUP
          value: {{ .Values.cloud.azure.resourceGroup }}
        {{- end }}
        - name: DISPATCHER_FILESTORAGE_PROVIDER
          value: {{ .Values.fileStorage.provider }}
        {{- if eq .Values.fileStorage.provider "azure" }}
        - name: DISPATCHER_FILESTORAGE_AZURE_ACCONTNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: fileStorageAzureAccountName
        - name: DISPATCHER_FILESTORAGE_AZURE_ACCONTKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: fileStorageAzureAccountKey
        - name: DISPATCHER_FILESTORAGE_AZURE_USEPROXY
          value: {{ .Values.fileStorage.azure.useProxy | quote }}
        {{- end }}
        - name: DISPATCHER_DBSTORAGE_PROVIDER
          value: {{ .Values.dbStorage.provider }}
        {{- if eq .Values.dbStorage.provider "mongodb" }}
        - name: DISPATCHER_DBSTORAGE_MONGODB_URI
          value: {{ .Values.dbStorage.mongodb.uri }}
        - name: DISPATCHER_DBSTORAGE_MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: dbStorageMongodbUsername
        - name: DISPATCHER_DBSTORAGE_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: dbStorageMongodbPassword
        {{- end }}
        - name: DISPATCHER_AMQP_PROVIDER
          value: {{ .Values.amqp.provider }}
        {{- if eq .Values.amqp.provider "servicebus" }}
        - name: DISPATCHER_AMQP_SERVICEBUS_NAMESPACE
          value: {{ .Values.amqp.servicebus.namespace }}
        {{- end }}
      {{- if .Values.module.config }}
        volumeMounts:
        - name: module-config
          mountPath: /etc/ion/module
      volumes:
      - name: module-config
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: module.yml
            path: config.yml
      {{- end }}
