{{- if .Values.service.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  {{- if .Values.service.ingress.annotations }}
  annotations:
{{ toYaml .Values.service.ingress.annotations | indent 4 }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
spec:
  rules:
  {{- range .Values.service.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" $ }}
          servicePort: {{ $.Values.service.port }}
  {{- end }}
  {{- if .Values.service.ingress.tls }}
  tls:
{{ toYaml .Values.service.ingress.tls | indent 4 }}
  {{- end }}
{{- end }}
